### ISSUE TITLE
require directive not supported "var d3 = require("d3-array");" in jandas/lib/DataFrame.js:9

### ISSUE THREAD

**Issue by dandickout** [frlender/Jandas#1]
var d3 = require("d3-array");
         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/yourname/Code/Jira-Data/node_modules/d3-array/src/index.js from /Users/yourname/Code/Jira-Data/node_modules/jandas/lib/DataFrame.js not supported.
Instead change the require of index.js in /Users/yourname/Code/Jira-Data/node_modules/jandas/lib/DataFrame.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/yourname/Code/Jira-Data/node_modules/jandas/lib/DataFrame.js:9:10)
    at Object.<anonymous> (/Users/yourname/Code/Jira-Data/node_modules/jandas/lib/Series.js:7:19)
    at Object.<anonymous> (/Users/yourname/Code/Jira-Data/node_modules/jandas/lib/cmm.js:6:16)
    at Object.<anonymous> (/Users/yourname/Code/Jira-Data/node_modules/jandas/lib/Index.js:3:13)
    at Object.<anonymous> (/Users/yourname/Code/Jira-Data/node_modules/jandas/lib/J.js:4:15) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by frlender** [comment]
Thanks for raising this issue. It turns out that d3-array does not work well with the Node environment. I have removed dependency on d3-array and used the simple-statistics package instead. Please check the latest 1.0.5 release. Let me know if this is still an issue.
